### ISSUE TITLE
Removed 320mb of mp4 from this repo

### ISSUE THREAD

**Issue by Haiz14** [Damaj301damaj-lol/damaj.tech#1]
Ran bfg cleaner https://github.com/rtyley/bfg-repo-cleaner, which made this repo 15mb big, here's the zip of repo https://github.com/Haiz14/damaj.tech/blob/main/damaj.tect.zip

Everything except those mp4 files are intact.
There's just one problem, you gotta delete this repo and use the zip repo or maybe just run bfg cleaner yourself (trust issues) and replace this repo with that.

**Comment by Haiz14** [comment]
When I pushed that repo, the push worked but while cloning the repo size remained 340mb

**Comment by Damaj301damaj-lol** [comment]
How about just a git clean instead, or just clone with `git clone --depth 1`, reduces it to 15 mb, i would like to preserve those old commits for historical reasons.

**Comment by Haiz14** [comment]
It's your repo, your choice. I always wanted to try bfg cleaner. It's not as good, like, I have to delete the repo to remove, I was just experimimemting.
